export const ConstantsLib = {
  GIVEN_NAMES: 'Full Sam',
  SURNAME: 'Ted',
  FULL_NAME: 'HOF TEST',
  ADDRESS_LINE_1: '100',
  ADDRESS_LINE_2: 'Tenth St',
  TOWN_OR_CITY: 'HULL',
  COUNTY: 'Greater Manchester',
  POSTCODE: 'M11 1HH',
  COUNTRY_UK: 'UK',
  TELEPHONE: '01616699548',
  SAS_HOF_EMAIL: 'test@example.com',
  DOB_1978: '01/01/1978',
  NATIONALITY: 'Spain',
  YESTERDAY_S_DATE: "yesterday's date",
  TEXT_VALUE: 'textValue',
  CONTACT_US_URL: 'https://www.gov.uk/contact-ukvi-inside-outside-uk',
  BIOMETRIC_RESIDENCE_PERMITS_URL: 'https://www.gov.uk/biometric-residence-permits',
  UPDATE_UK_VISAS_AND_IMMIGRATION_ACCOUNT_DETAILS_URL: 'https://www.gov.uk/update-uk-visas-immigration-account-details',
  VIEW_AND_PROVE_YOUR_IMMIGRATION_STATUS_URL: 'https://www.gov.uk/view-prove-immigration-status',
  GET_ACCESS_TO_EVISA_URL: 'https://www.gov.uk/get-access-evisa',
} as const;
